dr_index:
    path:     /
    defaults: { _controller: DRPlatformBundle:Art:index }

# TYPE

dr_type_index:
    path:     /type
    defaults: { _controller: DRPlatformBundle:Type:index }
    methods:  [GET]

dr_type_new:
    path:     /type/new
    defaults: { _controller: DRPlatformBundle:Type:new }
    methods:  [GET, POST]

dr_type_show:
    path:     /type/{id}
    defaults: { _controller: DRPlatformBundle:Type:show }
    methods:  [GET]

dr_type_edit:
    path:     /type/{id}/edit
    defaults: { _controller: DRPlatformBundle:Type:edit }
    methods:  [GET, POST]

dr_type_delete:
    path:     /type/{id}
    defaults: { _controller: DRPlatformBundle:Type:delete }
    methods:  [DELETE]

# FOLDER

dr_folder_index:
    path:     /folder
    defaults: { _controller: DRPlatformBundle:Folder:index }
    methods:  [GET]

dr_folder_new:
    path:     /folder/new
    defaults: { _controller: DRPlatformBundle:Folder:new }
    methods:  [GET, POST]

dr_folder_show:
    path:     /folder/{id}
    defaults: { _controller: DRPlatformBundle:Folder:show }
    methods:  [GET]

dr_folder_edit:
    path:     /folder/{id}/edit
    defaults: { _controller: DRPlatformBundle:Folder:edit }
    methods:  [GET, POST]

dr_folder_delete:
    path:     /folder/{id}
    defaults: { _controller: DRPlatformBundle:Folder:delete }
    methods:  [DELETE]